### ISSUE TITLE
TabError in ABC/workflow/rules/utils.smk 

### ISSUE THREAD

**Issue by 613weilin** [EngreitzLab/sc-E2G#1]
When I run "snakemake -j1 --use-conda", I get following errors:

> TabError in file <string>, line 6:
> inconsistent use of tabs and spaces in indentation (<string>, line 6)
>   File "/maps/projects/ralab_nnfc-AUDIT/people/lpm537/software/sc-E2G/workflow/Snakefile", line 28, in <module>
>   File "/maps/projects/ralab_nnfc-AUDIT/people/lpm537/software/sc-E2G/workflow/../ABC/workflow/Snakefile", line 11, in <module>
>   File "/maps/projects/ralab/people/lpm537/software/anaconda3/envs/scE2G_231121/lib/python3.12/[tokenize.py](http://tokenize.py/)", line 541, in _generate_tokens_from_c_tokenizer
>   File "/maps/projects/ralab/people/lpm537/software/anaconda3/envs/scE2G_231121/lib/python3.12/[tokenize.py](http://tokenize.py/)", line 537, in _generate_tokens_from_c_tokenizer

It seems that the line 5 of ABC/workflow/rules/utils.smk should use tab indentation instead of spaces indentation.

After fixing it, I get a SyntaxWarning:
> snakemake -j1 --use-conda
> /maps/projects/ralab_nnfc-AUDIT/people/lpm537/software/sc-E2G/ABC/workflow/rules/utils.smk:5: SyntaxWarning: invalid escape sequence '\d'
>   threshold="\d+\.\d+",

Should the line 5 in ABC/workflow/rules/utils.smk be 
`threshold="\\d+\\.\\d+"`

**Comment by atancoder** [comment]
Fixed as part of https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/pull/154
